services:
  - type: web
    name: flask-streamlit-app
    env: python
    buildCommand: pip install -r requirements.txt  # Runs the start.sh script to install dependencies and start both Flask and Streamlit
    startCommand: gunicorn -w 4 -b 0.0.0.0:8080 app:app

