services:
  - type: web
    name: flask-streamlit-app
    env: python
    plan: starter
    buildCommand: |
      # Install dependencies
      pip install -r requirements.txt
    startCommand: bash start.sh
    port: $PORT
