services:
  - type: web
    name: sentimental-analysis-reddit-app
    env: python
    plan: free
    buildCommand: pip install -i https://mirrors.aliyun.com/pypi/simple/ -r ./requirements.txt
    startCommand: python run.py
    python_version: 3.10
