services:
  - type: web
    name: flask-app
    env: python
    plan: starter
    buildCommand: |
      pip install -r requirements.txt
    startCommand: bash start.sh

  - type: web
    name: streamlit-app
    env: python
    plan: starter
    buildCommand: |
      pip install -r requirements.txt
    startCommand: python -m streamlit run streamlit.py --server.port 8502 --server.headless true
